### ISSUE TITLE
CosmWasm support for wallet-monitor 

### ISSUE THREAD

**Issue by PinchiDev** [PinchiDev/wallet-monitor#2]
# Implementing Support for CosmWasm Blockchains

## Project Description

This project aims to implement support for CosmWasm blockchains within Xlabs wallet-monitor library. This library facilitates the monitoring of balances across multiple wallets in various blockchains. In addition, to balance monitoring, the library will export these balances as Prometheus metrics and execute rebalancing strategies between wallets.

### Get Development Environment in a Working State
- [x] Install dependencies in /wallet-monitor and /src folders.
- [x] Compile the TypeScript files (tsc -w).
- [x] Make sure the build is running (npm run build).

### Get Testing Logic and Capacities in Place
- [x] Make a Keppler wallet and use the faucet to obtain some balance.
- [x] Check the balance in the blockchain explorer for the specific CosmWasm blockchain.

### Create the "CosmWasmWalletToolbox" class extending the "WalletToolbox" class in a new wallets file
- [x] Implement the connection logic to interact with the respective CosmWasm blockchain.
- [x] modify/create respective validations and methods for the cosmwasm data formats.
- [ ] test if the connection with the respective blockchain was successful and the correct values were passed.

### Implement Logic for Pulling Native Balance 
- [ ] Implement the logic for pulling the native balance of the test wallet in the respective CosmWasm blockchain.
- [ ] test pullCosmWasmNativeBalance and compare the balance obtained with the block explorer data.

### Implement Logic for Pulling Token Balance
- [ ] Implement the logic for pulling the token balance of the test wallet in the respective CosmWasm blockchain.
- [ ] test pullCosmWasmTokenBalance and compare the balance obtained with the block explorer data.

### Implement Logic for Pulling Token Data 
- [ ] Implement the logic for pulling token data of a certain token in the respective CosmWasm blockchain.
- [ ] test pullCosmWasmTokenData check the data.

### Implement Logic for Getting a Public Address from a private key
- [ ] Implement the logic to transform a private key from a cosmwasm wallet into a public address.
- [ ] test getAdressFromPrivateKey checking the existence of the address in the explorer.

### Implement Logic for Transferring Native Balance
- [ ] Implement the logic for transferring native balance between wallets in CosmWasm blockchains.
- [ ] test transferNativeBalance and compare the balances for the respective wallets in the block explorer.

### Write Project Wrap-up and Plan Next Steps
- [ ] Document the implementation and achievements.
- [ ] Plan the next steps and potential enhancements.

## Contributing
Please feel free to comment on this issue, this is a work in progress from a developer in progress so any contributions are welcome.

---

The implementation of this project will be pivotal in providing comprehensive support for the emerging technology of CosmWasm blockchains. It will not only facilitate the seamless monitoring of wallet balances but also allow the execution of complex balancing strategies. Feel free to join the development!.

**Comment by nunyvega** [comment]
@PinchiDev acordate de ir comentando lo que haces en cada paso, las piedras que te encontrás, como las zafás, etc. Pingueanos con las cosas con las que necesites ayuda, subí screenshots, tus pasos. Es en ese lugar donde se encuentra el valor de esto. 

We're here to give you support and help you become a power ranger.

**Comment by solanoepalacio** [comment]
Thanks so much for helping out guys! you are awesome! these are exactly the steps you need to follow :heart:

**Comment by solanoepalacio** [comment]
I would really appreciate taking this issue to the actual wallet monitor. It would be great to use it as a template in the repo. This way it would be easy for anyone who needs to add support for a chain they want to monitor :muscle:

**Comment by PinchiDev** [comment]
@solanoepalacio Great!, I will try to improve it further so we can take it to the main repro.

**Comment by PinchiDev** [comment]
@solanoepalacio Regarding the implementation of the SigningCosmWasmClient I'm starting to think the correct way to use it would be to create an instance directly in the balances/cosmwasm/index given it works with an asynchronous constructor.  what do you think?

**Comment by nunyvega** [comment]
@PinchiDev, great job on your progress so far! As you continue your coding journey, I'd like to provide some recommendations. It's always beneficial to lean towards over-communication rather than under-communication. Here are some concise steps that will help you move forward efficiently and iteratively:

- [x] Transfer this issue to the main wallet monitor repository. You can simply copy and paste its content.
- [x] Before the **_Project Description_** section of the newly copied issue, insert a brief paragraph. Mention that you'll be documenting your steps, and the purpose of this documentation is to guide future devs during their wallet setup process.
- [ ] Set up a fresh instance of the wallet monitor on your local machine. As you do this, document each step. (Tip: The `history` command in your terminal will display recently executed commands, which can be helpful for documentation).
- [ ] Follow a similar approach for the Keplr wallet setup, documenting each step.
- [ ] Create your first PR. It should introduce a function that connects and authenticates with Keplr. In your PR, provide clear instructions for testing this functionality.

Remember, iterative progress is key. Taking small, meaningful steps will ensure you build a solid foundation. Keep up the good work!

**Comment by nunyvega** [comment]
Here's a template that you can use as guidance to create your PR description:

---

#### **Description:**
Briefly describe the changes introduced by this PR. This section should clearly express the rationale and motivation behind the changes, any related issues (like the issue used to track your progress), and the impact of the changes.

```
[Provide a concise summary of the changes in this PR.]
```
One good advice about descriptions in PRs that I got when I was starting to code was to think about the phrase "_If this PR is merged, it will ....._" and only adding the part in the dots.

---

#### **Testing Steps:**

1. **Preconditions**:  
   - [ ] List any setup or precondition required for testing.
   - [ ] Are there any dependencies or services that need to be running? (like a Keplr wallet)

2. **Procedure**:  
   Detail the exact steps to validate the changes. These steps should allow any person to replicate the testing process.
   ```
   1. Navigate to ...
   2. Click on ...
   3. Observe ...
   ```

3. **Expected Outcome**:  
   Describe the expected behavior or result after following the testing steps.
 E.g., "After clicking on the button, the modal should appear with the user's information."


---

#### **Additional Information:**
Include any additional information, like dependencies introduced, any breaking changes, screenshots or GIFs (if they provide value), and anything else that's relevant.

---

You can customize it further based on your needs.

**Comment by PinchiDev** [comment]
Thanx folks for all the feedback and disposition for helping a new developer

Based on the previous discussion on this issue I moved this issue to the main repo and I  will continue working there.
https://github.com/XLabs/wallet-monitor/issues/93

@nunyvega I marked as completed the first two items on the list of recommended next tasks. I will continue tackling them in the main repo.
